[package]
name = "opai-rust"
version = "0.0.1"
authors = ["Kurnevsky Evgeny <kurnevsky@gmail.com>"]
license = "GPL-3.0"

[dependencies]
rand = "0.3.9"
time = "0.1.32"
log = "0.3.1"
log4rs = "0.3.3"
num_cpus = "0.2.6"
rustc-serialize = "0.3.15"
toml = "0.1.21"

[dev-dependencies]
quickcheck = "0.2.20"

[profile.dev]
opt-level = 0
lto = false
debug = true

[profile.release]
opt-level = 3
lto = true
debug = false
